PACKAGE = "com.nightfire.adapter.converter.util"

FILES = \
	DepthFirstTreeWalker.java \
	PrintVisitor.java \
	TreeWalker.java \
	Visitor.java \
	XMLVisitor.java \

TOP=../../../../..

ifndef MAKE_HOME
MAKE_HOME=$(TOP)/makefiles
endif
include $(MAKE_HOME)/package.mk