PACKAGE = "com.nightfire.comms.socket"

FILES = \
	ClientSocketRequestHandler.java \
	SocketListener.java \
	SocketCommServer.java \
	SocketCommAdapter.java \
	BasicClientSocketRequestHandler.java \
	EAPCommAdapter.java \

TOP=../../../..

ifndef MAKE_HOME
MAKE_HOME=$(TOP)/makefiles
endif
include $(MAKE_HOME)/package.mk
