PACKAGE = "com.nightfire.comms.util"

PACKAGES = \
	ftp \
	http \

FILES = \
	RequestHandlerClient.java \
	CorbaClient.java \

TOP=../../../..

ifndef MAKE_HOME
MAKE_HOME=$(TOP)/makefiles
endif
include $(MAKE_HOME)/package.mk
