PACKAGE = "com.nightfire.adapter.util"

FILES = \
	XmlMangler.java \
	ILECEntityResolver.java \
	XMLStringCompactor.java \
	XMLCompactorUtil.java \
	ConditionInterpreter.java \
	ConditionParser.java \
	IfConditionChecker.java \
	SSLPortabilityLayer.java \
	FixedFormat.java \
	MapContainer.java \
	DeepCopyUtil.java \


TOP=../../../..

ifndef MAKE_HOME
MAKE_HOME=$(TOP)/makefiles
endif
include $(MAKE_HOME)/package.mk
