PACKAGE = "com.nightfire.comms.jms.handler"

FILES = \
	JMSConsumerRequestHandler.java \

TOP=../../../../..

ifndef MAKE_HOME
MAKE_HOME=$(TOP)/makefiles
endif
include $(MAKE_HOME)/package.mk