PACKAGE="com.nightfire.servers"

FILES = \
	ServerBase.java \
	AdminClient.java \

PACKAGES = \
	CosEvent \



TOP=../../..

ifndef MAKE_HOME
MAKE_HOME=$(TOP)/makefiles
endif
include $(MAKE_HOME)/package.mk
