PACKAGE = "com.nightfire.adapter.errorhandler"

FILES = \
	ErrorTranslator.java \
	ErrorFilter.java \
	ErrorDebugLogger.java \
	DriverErrorExtractor.java \

TOP=../../../..

ifndef MAKE_HOME
MAKE_HOME=$(TOP)/makefiles
endif
include $(MAKE_HOME)/package.mk
