package com.nightfire.comms.ia3.asn.issue3; // machine generated code. DO NOT EDIT

import cryptix.asn1.lang.*;

public class UniqueIdentifier extends Choice {

   // Constructor(s)
   // -------------------------------------------------------------------------

   /**
    * Constructs a new instance of this type with a blank Name.
    */
   public UniqueIdentifier() {
      super("", null);
   }

   /**
    * Constructs a new instance of this type with a designated Name.
    *
    * @param name the designated Name for this new instance.
    */
   public UniqueIdentifier(String name) {
      super(name, null);
   }

   /**
    * Constructs a new instance of this type with a designated Name and Tag.
    *
    * @param name the designated Name for this new instance.
    * @param tag the designated tag for this new instance.
    */
   public UniqueIdentifier(String name, Tag tag) {
      super(name, tag);
   }

   /**
    * Constructs a new instance of this type with a trivial Name and an
    * initial value.
    *
    * @param value the initial value of this instance.
    */
   public UniqueIdentifier(Choice value) {
      this("", value);
   }

   /**
    * Constructs a new instance of this type with a designated Name and an
    * initial value.
    *
    * @param name the designated Name for this new instance.
    * @param value the initial value of this instance.
    */
   public UniqueIdentifier(String name, Choice value) {
      this(name, null, value);
   }

   /**
    * Constructs a new instance of this type given its Name, Tag and initial
    * value.
    *
    * @param name the designated Name for this new instance.
    * @param tag the specific tag for this instance.
    * @param value the initial value for this instance.
    */
   public UniqueIdentifier(String name, Tag tag, Choice value) {
      super(name, tag, value == null ? null : value.value());
   }

   // Constants and variables
   // -------------------------------------------------------------------------


   // Over-loaded implementation of methods defined in superclass
   // -------------------------------------------------------------------------

   protected void initInternal() {
      super.initInternal();

      IType isaSegment = new OctetString("isaSegment");
      components.add(isaSegment);
      IType textHash = new OctetString("textHash", new Tag(Tag.CONTEXT, 0, true));
      components.add(textHash);
      IType xmlHash = new OctetString("xmlHash", new Tag(Tag.CONTEXT, 1, true));
      components.add(xmlHash);
   }

   // Accessor methods
   // -------------------------------------------------------------------------

   public OctetString getIsaSegment() {
      return (OctetString) components.get(0);
   }

   public void setIsaSegment(OctetString obj) {
      OctetString it = getIsaSegment();
      it.value(obj.value());
      components.set(0, it);
   }

   public OctetString getTextHash() {
      return (OctetString) components.get(1);
   }

   public void setTextHash(OctetString obj) {
      OctetString it = getTextHash();
      it.value(obj.value());
      components.set(1, it);
   }

   public OctetString getXmlHash() {
      return (OctetString) components.get(2);
   }

   public void setXmlHash(OctetString obj) {
      OctetString it = getXmlHash();
      it.value(obj.value());
      components.set(2, it);
   }

   // CHOICE-specific convenience methods
   // -------------------------------------------------------------------------

   /**
    * Returns true iff this CHOICE instance has been decoded, and its (only)
    * concrete alternative is the designated one. False otherwise.
    *
    * @return true iff this CHOICE instance has been decoded, and its (only)
    * concrete alternative is the designated one. False otherwise.
    */
   public boolean isIsaSegment() {
      return !getIsaSegment().isBlank();
   }
   /**
    * Returns true iff this CHOICE instance has been decoded, and its (only)
    * concrete alternative is the designated one. False otherwise.
    *
    * @return true iff this CHOICE instance has been decoded, and its (only)
    * concrete alternative is the designated one. False otherwise.
    */
   public boolean isTextHash() {
      return !getTextHash().isBlank();
   }
   /**
    * Returns true iff this CHOICE instance has been decoded, and its (only)
    * concrete alternative is the designated one. False otherwise.
    *
    * @return true iff this CHOICE instance has been decoded, and its (only)
    * concrete alternative is the designated one. False otherwise.
    */
   public boolean isXmlHash() {
      return !getXmlHash().isBlank();
   }
}

// Generated by the cryptix ASN.1 kit on Tue Aug 24 11:57:40 PDT 2004
