/*
 * Copyright (c) 2004 NeuStar, Inc. All rights reserved.
 * $Header: $
 */
package com.nightfire.comms.soap;


/**
 * Interface that will serve as proxy to gateways and managers
 */
public interface SOAPResponseHandler extends java.rmi.Remote
{

  /**
   * Method to post reponses generated by the system. The end user is required to implement the
   * wsdl associated with this interface. This class is being provided here only for internal
   * testing purposes. All the events received on event channels that a customer is registered for
   * will be delivered by this SOAP call on the customer's SOAP end-point. It is assumed
   * that there will be only one SOAP end-point for each customer.
   *
   * @param eventChannelName Name of the event channel where this message was retrieved from.
   * @param message The message retrieved from the event channel.
   *
   * @exception java.rmi.RemoteException If there is an error processing the request.
   */
  public void processEvent( String eventChannelName, String event ) throws java.rmi.RemoteException;

}
