PACKAGE = "com.nightfire.idl.RequestHandlerPackage"

FILES = \
	NullResultException.java \
	NullResultExceptionHelper.java \
	NullResultExceptionHolder.java \
	UsageDescription.java \
	UsageDescriptionHelper.java \
	UsageDescriptionHolder.java \
	UsageDescriptionsHelper.java \
	UsageDescriptionsHolder.java \

TOP=../../../..
ifndef MAKE_HOME
MAKE_HOME=$(TOP)/makefiles
endif
include $(MAKE_HOME)/package.mk


