PACKAGE = "com.nightfire.framework.transaction.unittest"



FILES = \
	TestTransactionParticipant1.java \
	TestTransactionParticipant2.java \
	Tester1.java \
	Tester2.java \


TOP=../../../../..

ifndef MAKE_HOME
MAKE_HOME=$(TOP)/makefiles
endif

include $(MAKE_HOME)/package.mk


