#
# Makefile
#
# $Header: //nfcommon/R4.4/com/nightfire/framework/resource/Makefile#1 $
#

PACKAGE = "com.nightfire.framework.resource"

FILES = \
	ResourceException.java \
	ResourcePool.java \
	

TOP=../../../..

ifndef MAKE_HOME
MAKE_HOME=$(TOP)/makefiles
endif
include $(MAKE_HOME)/package.mk
