PACKAGE = "com.nightfire.framework.util"

FILES =						\
	NFConstants.java			\
	CustomerContext.java			\
	CSVFileConsumer.java			\
	CSVFileReader.java			\
	Crypt.java				\
	DateUtils.java				\
	ProcessInfo.java			\
	OSProcessInfo.java			\
	Debug.java				\
	MetricsAgent.java			\
	FileCache.java				\
	FileUtils.java				\
	FrameworkException.java			\
	NVPair.java				\
	NVPairContainer.java			\
	ObjectFactory.java			\
	Performance.java			\
	SetEnvironment.java			\
	SourceID.java				\
	StartClass.java				\
	StringTransformer.java			\
	StringUtils.java			\
	TokenDataSource.java			\
	TokenReplacer.java			\
	NFNotifier.java				\
	NFObserver.java				\
	PropUtils.java				\
	Lock.java				\
	ReadWriteLock.java			\
	RegexUtils.java				\
	ParsingTokenizer.java			\
	JavaCompiler.java			\
	FactoryCacheBase.java			\
	MessageData.java			\
	TimedWatcher.java			\
	SyncLock.java			\
	URLUtils.java				\

TOP=../../../..

ifndef MAKE_HOME
MAKE_HOME=$(TOP)/makefiles
endif
include $(MAKE_HOME)/package.mk
