PACKAGE = "com.nightfire.comms.handlers"

FILES = \
	RequestHandlerBase.java \
	RequestHandlerBaseException.java \
    RequestHandlerBaseExceptionType.java \


TOP=../../../..

ifndef MAKE_HOME
MAKE_HOME=$(TOP)/makefiles
endif
include $(MAKE_HOME)/package.mk