PACKAGE = "com.nightfire.framework.converter.edi"

PACKAGES = \
	util \

FILES = \
	SimpleEDITokenTypes.java \
	EDITokenTypes.java \
	EDI4020RespParserTokenTypes.java \
	EDI3070RespParserTokenTypes.java \
	SimpleEDINodeVisitor.java \
	EDINodeVisitorContext.java \
	EDINodeVisitor.java \
	EDItoXMLConverter.java \
	ResponseEDItoXMLConverter.java \
	XMLtoEDIConverter.java \
	EDIMessageConstants.java \
	EDIDelimiterReplacer.java \
	EDIDelimiters.java \
	EDIDelimiterExtractor.java \
	XMLtoEDIConverterProcessor.java \
	EDIValidationFailureProcessor.java \



TOP=../../../../..

ifndef MAKE_HOME
MAKE_HOME=$(TOP)/makefiles
endif
include $(MAKE_HOME)/package.mk
