PACKAGE = "com.nightfire.router.messagedirector"

FILES = \
	MessageDirector.java \
	MessageDirectorBase.java \
	MessageDirectorFactory.java \
	IlecTypeDirector.java \
	CicOperationDirector.java \
	ActionDirector.java \

TOP=../../../..

ifndef MAKE_HOME
MAKE_HOME=$(TOP)/makefiles
endif
include $(MAKE_HOME)/package.mk

