PACKAGE = "com.nightfire.comms.ia.asn.msg"

FILES = \
	IABasicEDI.java \
	IABasicReceipt.java \
	IAGeneric.java \
	IAStatus.java \

TOP=../../../../../..

ifndef MAKE_HOME
MAKE_HOME=$(TOP)/makefiles
endif
include $(MAKE_HOME)/package.mk
