PACKAGE = "com.nightfire.spi.neustar_soa.adapter.handler"

FILES = \
	AssociationReplyHandler.java \
	AssociationRequestRetry.java \
	DownloadRecoveryReplyHandler.java \
	DownloadRecoveryRequestRetry.java \
	GenericReplyHandler.java \
	NewSessionReplyHandler.java \
	NewSessionRetry.java \
	NotificationHandler.java \
	RecoveryCompleteReplyHandler.java \
	RecoveryHandlerBase.java \
	RecoveryReplyHandler.java \
	RecoveryRequestRetry.java \
	Retry.java \
	TimeoutTimerTask.java \
	ServiceProvidersDataSwimProcessingRecoveryRetry.java \
	ServiceProvidersDataSwimProcessingRecoveryReplyHandler.java \
	RecoverySwimProcessingRecoveryRetry.java \
	RecoveryReplySwimProcessingRecoveryReplyHandler.java \
	NetworkDataSwimProcessingRecoveryReplyHandler.java \
	NetworkDataSwimProcessingRecoveryRetry.java \
	WaitingHandlers.java \
	TimeBasedDownloadRecoveryReplyHandler.java \
	TimeBasedDownloadRecoveryRequestRetry.java \
	TimeBasedRecoveryHandlerBase.java \
	TimeBasedRecoveryReplyHandler.java \
	TimeBasedRecoveryRequestRetry.java 

TOP=../../../../../..

ifndef MAKE_HOME
MAKE_HOME=$(TOP)/makefiles
endif
include $(MAKE_HOME)/package.mk

