PACKAGE = "com.nightfire.comms.util.ftp.ssl"

FILES = \
	ConnectionInfo.java \
	FileInfo.java \
	FtpSslCommInterface.java \
	FtpSslCommConnector.java \
	FtpSslLayerInterconnect.java


TOP=../../../../../..

ifndef MAKE_HOME
MAKE_HOME=$(TOP)/makefiles
endif
include $(MAKE_HOME)/package.mk
