PACKAGE="com.nightfire.manager.common"

TOP=../../../..

PACKAGES = \
	util \
	state \
	servicehandler \

FILES = \
	ManagerConstants.java \
	CommonEventNames.java \


ifndef MAKE_HOME
MAKE_HOME=$(TOP)/makefiles
endif

include $(MAKE_HOME)/package.mk
