
PACKAGE="com.nightfire.framework.xrq.sql"

PACKAGES = \
	clauses \

FILES = \
	SQLResultSetSerializer.java \
	SQLExecutor.java \
	

TOP=../../../../..
ifndef MAKE_HOME
MAKE_HOME=$(TOP)/makefiles
endif
include $(MAKE_HOME)/package.mk
