PACKAGE = "com.nightfire.spi.common"

PACKAGES = \
	communications \
	driver \
	supervisor

FILES = \
	HeaderNodeNames.java

TOP=../../../..

ifndef MAKE_HOME
MAKE_HOME=$(TOP)/makefiles
endif
include $(MAKE_HOME)/package.mk

