PACKAGE = "com.nightfire.framework.state.test"

FILES = \
	OrderStateMachine.java \
	Order.java \
	StateSent.java \
	StateAck.java \
	StateCompleted.java \
	StateZero.java \
	StateOne.java \
	StateTwo.java \
	StateThree.java \
	StateFour.java \
	OddEvenStateMachine.java \
	Tester1.java \


TOP=../../../../..

ifndef MAKE_HOME
MAKE_HOME=$(TOP)/makefiles
endif
include $(MAKE_HOME)/package.mk
