PACKAGE = "com.nightfire.comms.corba"

FILES = \
	CorbaServer.java \
	AsyncCorbaServer.java \
	SyncCorbaServer.java \
	AsyncCorbaClient.java \
	SyncCorbaClient.java \
	RequestHandlerClient.java \
	MultiChannelAsyncClient.java \



TOP=../../../..

ifndef MAKE_HOME
MAKE_HOME=$(TOP)/makefiles
endif
include $(MAKE_HOME)/package.mk
