PACKAGE = "com.nightfire.comms.util.ftp"

FILES= \
	FtpException.java

PACKAGES = \
	ssl	

TOP=../../../../..

ifndef MAKE_HOME
MAKE_HOME=$(TOP)/makefiles
endif
include $(MAKE_HOME)/package.mk
