PACKAGE="com.nightfire.spi.neustar_soa.rules"

FILES = \
	AllowableActions.java \
	Context.java \
	RuleSetLocator.java \
	SOACustomDBFunctions.java \
	SOACustomSvDBFunctions.java \
	SOACustomNetworkDBFunctions.java \


TOP=../../../../..
ifndef MAKE_HOME
MAKE_HOME=$(TOP)/makefiles
endif
include $(MAKE_HOME)/package.mk