/*
 * Copyright(c) 2001 NightFire Software, Inc.
 * All rights reserved.
 */

package com.nightfire.webgui.core.tag;

import com.nightfire.webgui.core.ServletConstants;

/**
 * PageContants contains the contants used accross JSP pages
 */
public interface TagConstants
{


    /**
     * Cascading Style Sheet class names used when generating
     * html tags.
     */
    public static final String CLASS_AUTO_GENERATED       = "AutoGenerated";
    public static final String CLASS_ERROR                = "Error";
    public static final String CLASS_MSG_HEADING          = "MessageHeading";
    public static final String CLASS_FORM_HEADING         = "FormHeading";
    public static final String CLASS_SECTION_HEADING      = "SectionHeading";
    public static final String CLASS_SUBSECTION_HEADING   = "SubSectionHeading";
    public static final String CLASS_FIELD_TABLE          = "FieldTable";
    public static final String CLASS_FIELD_LABEL_REQUIRED = "FieldLabelRequired";
    public static final String CLASS_FIELD_LABEL_REQUIRED_ALWAYS = "FieldLabelRequiredAlways";
    public static final String CLASS_FIELD_LABEL_CONDITIONAL = "FieldLabelConditional";
    public static final String CLASS_FIELD_LABEL_OPTIONAL =  "FieldLabelOptional";
    public static final String CLASS_FIELD_LABEL_PROHIBITED = "FieldLabelProhibited";
    public static final String CLASS_FIELD_LABEL_REPLICATE = "AddReplicate";

    public static final String CLASS_TABLE_LAYOUT         = "LayoutTable";
    public static final String CLASS_FORM_TABLE           = "FormTable";
    public static final String CLASS_SIMPLEFORM_TABLE     = "SimpleFormTable";
    public static final String CLASS_SECTION_TABLE        = "SectionTable";
    public static final String CLASS_FIELD_CONTROL        = "FieldControl";

    public static final String CLASS_FIELDGRP_TABLE       = "FieldGrpTable";
    public static final String CLASS_FIELDGRP_HEADING     = "FieldGrpHeading";
    public static final String CLASS_SUBSEC_TABLE         = "SubSectionOuterTable";
    public static final String CLASS_SUBSEC               = "SubSection";

    public static final String CLASS_BTN_TABLE            = "ButtonTable";
    public static final String CLASS_BTN_BOX              = "ButtonBox";
    public static final String CLASS_TREE_TABLE           = "TreeTable";
    public static final String CLASS_TREE_ROW_ROOT        = "TreeRoot";
    public static final String CLASS_TREE_VISIBLE         = "TreeVisible";
    public static final String CLASS_TREE_ROW_NODE        = "TreeNode";
    public static final String CLASS_TREE_SELECTED        = "TreeSelected";
    public static final String CLASS_TREE_TEXT            = "TreeText";
    public static final String CLASS_COLUMN_TABLE         = "ColumnTable";
    public static final String CLASS_INNER_SECTION_TABLE  = "InnerSectionTable";
    public static final String CLASS_BORDER_CELL          = "BorderCell";
    public static final String CLASS_FIELD_CHECK_BOX      = "CheckBox";
    public static final String CLASS_GOTO_SECTION         = "GotoSection";
    public static final String CLASS_GOTO_FORM            = "GotoForm";
    public static final String CLASS_GOTO_ICONS           = "GoToIcons";
    public static final String CLASS_LEFT_PADDING         = "leftPadding";
    public static final String CLASS_DISABLED_INPUT       = "disabledInput";

    public static final String CLASS_SEARCHRESULTS_TABLE  = "searchResults";
    public static final String CLASS_NONSORTABLE          = "NotSortable";
    public static final String CLASS_SORTABLE             = "Sortable";


    public static final String CLASS_ERROR_SET            = "ErrorCollection";
    public static final String CLASS_ERROR_RULE           = "RuleError";
    public static final String CLASS_ERROR_MSG            = "RuleErrorMsg";
    public static final String CLASS_ERROR_HEADING        = "RuleErrorHeading";

    public static final String CLASS_TAB_MENU             = "TabMenu";
    public static final String CLASS_TAB_TOP              = "TabTop";
    public static final String CLASS_TAB_TOP_LEFT         = "TabTopLeft";
    public static final String CLASS_TAB_LEFT             = "TabLeft";
    public static final String CLASS_TAB_RIGHT            = "TabRight";
    public static final String CLASS_TAB_TOP_RIGHT        = "TabTopRight";
    public static final String CLASS_TAB_TEXT             = "TabText";
    public static final String CLASS_TAB_TEXT_SELECTED    = "SelectedTabText";
    public static final String CLASS_TAB_BOTTOM           = "TabBottom";
    public static final String CLASS_TAB_BOTTOM_SELECTED  = "SelectedTabBottom";

    /**
     *  XML Path separator character
     */
    public static final String PATH_SEP = ".";

    // Form Names

    /**
     * header field used to indicate the current form id that is selected.
     */
    public static final String FORM_ID_TAG          = ServletConstants.NF_FIELD_HEADER_PREFIX + "FormId";

    /**
     * header field used to indicate the current form index that is selected.
     */
    public static final String FORM_IDX_TAG         = ServletConstants.NF_FIELD_HEADER_PREFIX + "FormIndex";

    /**
     * header field used to indicate the current section id that is selected.
     */
    public static final String SECTION_ID_TAG       = ServletConstants.NF_FIELD_HEADER_PREFIX + "SectionId";

    /**
     * header field used to indicate the current section index that is selected.
     */
    public static final String SECTION_IDX_TAG      = ServletConstants.NF_FIELD_HEADER_PREFIX + "SectionIndex";

    /**
     * header field used to hold an xml path used by some actions.
     */
    public static final String XML_PATH_TAG         = ServletConstants.NF_FIELD_HEADER_PREFIX + "XMLPath";

    // actions
    /**
     * action value that indicates that the node value from XML_PATH_TAG should be added to
     * the current message.
     */
    public static final String ADD_NODE_ACTION_NAME  =   "AddNode";

    /**
     * action value that indicates that the node value from XML_PATH_TAG should be deleted from
     * the current message.
     */
    public static final String DELETE_NODE_ACTION_NAME = "DeleteNode";


    /**
     * common images used by jsp pages
     */
    public static final String IMG_ADD_SECTION       =
        "images/AddSectionButton.gif";
    public static final String IMG_DEL_SECTION       =
        "images/DeleteSectionButton.gif";
    public static final String IMG_ADD_FORM          =
        "images/AddFormButton.gif";
    public static final String IMG_DEL_FORM          =
        "images/DeleteFormButton.gif";
    public static final String IMG_ADD_ROW           =
        "images/AddRowButton.gif";
    public static final String IMG_DEL_ROW           =
        "images/DeleteRowButton.gif";
    public static final String IMG_SUBMIT            =
        "images/SubmitButton.gif";
    public static final String IMG_RESET             =
        "images/ResetButton.gif";
    public static final String IMG_SHIM             =
        "images/shim.gif";
    /**
     * location for the view button
     */
    public static final String IMG_VIEW_BUTTON    = "images/ViewButton.gif";

    public static final String IMG_SEARCH_TITLE    = "images/SearchTitle.gif";

    public static final String IMG_SORT_DESC    = "images/sort-desc.gif";

    public static final String IMG_SORT_ASC    = "images/sort-asc.gif";

    public static final String IMG_LOCK   = "images/Lock.gif";

    public static final String IMG_UNLOCK = "images/Unlock.gif";

    public static final String IMG_ETC = "images/ETCButton.gif";


    /**
     * value for a html return line string.
     */
    //public static final String NL =                "\r\n";
    public static final String NL =                "";

    /**
     * Hidden data type to indicate that this is a hidden field.
     */
     public static final String DATA_TYPE_HIDDEN   = "hidden";

    /**
     * Data type to indicate that this is a RANGE field.
     */
     public static final String DATA_TYPE_RANGE   = "RANGE";


	 /**
	 * Data type to indicate that this is a RANGE field but with optional time
	 */
     public static final String DATA_TYPE_RANGE_OPTIONAL = "RANGE_OPTIONAL_TIME";

     /**
	 * Data type to indicate that this is a RANGE field but with optional time
	 */
     public static final String DATA_TYPE_REL_RANGE_OPTIONAL = "REL_RANGE_OPTIONAL_TIME";


    /**
     * Indicates how field labels should be displayed
     * Default is false and to use the displayNames.
     *
     */
    public static final String DISPLAY_FIELD_MODE_PROP = "FIELD_DISPLAY_MODE";

    /**
     * Indicates that displaynames  should be used for field labels.
     * Possible value for DISPLAY_FIELD_MODE_PROP
     *
     */
    public static final String DISPLAYNAME_LABEL    ="displayNames";

    /**
     * Indicates that abbreviations  should be used for field labels.
     * Possible value for DISPLAY_FIELD_MODE_PROP
     */
    public static final String ONLY_ABBREVS_LABEL    ="abbrevs";

    /**
     * Indicates that displaynames and abbreviations
     * should be used for field labels.
     * Possible value for DISPLAY_FIELD_MODE_PROP
     *
     */
    public static final String BOTH_LABEL    ="both";


    public static final String UTC_TIMEZONE    ="UTC";

}
