PACKAGE="com.nightfire.spi.neustar_soa.portps"

FILES = \
	PortingInfoType.java \
	PortingRequestType.java \
	PortingResponseType.java \
	PortpsService.java \
	PortpsServiceBindingStub.java \
	PortpsServiceLocator.java \
	PortpsServicePort.java \
	PORTPSServiceStubClient.java \
	TNResponseType.java \

TOP=../../../../..
ifndef MAKE_HOME
MAKE_HOME=$(TOP)/makefiles
endif
include $(MAKE_HOME)/package.mk
