
PACKAGE="com.nightfire.framework.xrq.utils"


FILES = \
	SwapIOAccess.java \
	RecordSerializer.java \
	XrqLanguageResource.java \
	ChainedHashMap.java \
	

TOP=../../../../..
ifndef MAKE_HOME
MAKE_HOME=$(TOP)/makefiles
endif
include $(MAKE_HOME)/package.mk
