PACKAGE = "com.nightfire.comms.servicemgr.helper"

FILES = \
    MessageProcessorExecutor.java \

TOP=../../../../..

ifndef MAKE_HOME
MAKE_HOME=$(TOP)/makefiles
endif
include $(MAKE_HOME)/package.mk
