PACKAGE = "com.nightfire.comms.rmi"

FILES = \
	RMIServer.java \
	RMIServer_Skel.java \
	RMIServer_Stub.java \
	AsyncRMIServer.java \
	SyncRMIServer.java \
	RMIBinaryRequestHandler.java \
	RMIRequestHandlerClient.java \
	RMIBinaryRequestHandlerImpl.java \
	RMIRequestHandlerImpl.java \
	RMIBinaryRequestHandlerClient.java \

RMI = \
	RMIServer.class \

TOP=../../../..


ifndef MAKE_HOME
MAKE_HOME=$(TOP)/makefiles
endif
include $(MAKE_HOME)/package.mk
