PACKAGE = "com.nightfire.comms.connectors"

FILES = \
	Constants.java\
	MessageListener.java\
	NFConManager.java\
	NFDataTranslator.java\
	NFEventSource.java\
	NFEventSourceBase.java\
	NFEventSourceDef.java\
	NFEventSourceRep.java\
	NFEventSourceRepBeanInfo.java\
	NFFilterTranslator.java\
	NFSource.java\
	NFSourceBase.java\
	NFSourceDef.java\
	NFSourceRep.java\
	NFSourceRepBeanInfo.java\
	NFVitriaServer.java\
	PushConsumerCallBackImpl.java\
	SimpleCorbaClient.java\
	SimpleEventPusher.java\

TOP=../../../..

ifndef MAKE_HOME
MAKE_HOME=$(TOP)/makefiles
endif
include $(MAKE_HOME)/package.mk
