PACKAGE = "com.nightfire.comms.servicemgr"

PACKAGES = \
	helper \

FILES = \
    JMSQueueConsumerManager.java \
    ServerManagerBase.java \
    ServerManagerFactory.java \

TOP=../../../..

ifndef MAKE_HOME
MAKE_HOME=$(TOP)/makefiles
endif
include $(MAKE_HOME)/package.mk
