package com.nightfire.comms.ia3.asn.issue2; // machine generated code. DO NOT EDIT

import cryptix.asn1.lang.*;

public class IABasicReceipt extends Sequence {

   // Constructor(s)
   // -------------------------------------------------------------------------

   /**
    * Constructs a new instance of this type with a blank Name.
    */
   public IABasicReceipt() {
      super("", new Tag(Tag.SEQUENCE));
   }

   /**
    * Constructs a new instance of this type with a designated Name.
    *
    * @param name the designated Name for this new instance.
    */
   public IABasicReceipt(String name) {
      super(name, new Tag(Tag.SEQUENCE));
   }

   /**
    * Constructs a new instance of this type with a designated Name and Tag.
    *
    * @param name the designated Name for this new instance.
    * @param tag the designated tag for this new instance.
    */
   public IABasicReceipt(String name, Tag tag) {
      super(name, tag);
   }

   /**
    * Constructs a new instance of this type with a trivial Name and an
    * initial value.
    *
    * @param value the initial value of this instance.
    */
   public IABasicReceipt(Sequence value) {
      this("", value);
   }

   /**
    * Constructs a new instance of this type with a designated Name and an
    * initial value.
    *
    * @param name the designated Name for this new instance.
    * @param value the initial value of this instance.
    */
   public IABasicReceipt(String name, Sequence value) {
      this(name, new Tag(Tag.SEQUENCE), value);
   }

   /**
    * Constructs a new instance of this type given its Name, Tag and initial
    * value.
    *
    * @param name the designated Name for this new instance.
    * @param tag the specific tag for this instance.
    * @param value the initial value for this instance.
    */
   public IABasicReceipt(String name, Tag tag, Sequence value) {
      super(name, tag, value == null ? null : value.value());
   }

   // Constants and variables
   // -------------------------------------------------------------------------


   // Over-loaded implementation of methods defined in superclass
   // -------------------------------------------------------------------------

   protected void initInternal() {
      super.initInternal();

      IType iaReceiptMessage = new ObjectIdentifier("iaReceiptMessage");
      components.add(iaReceiptMessage);
      IType receiptContent = new ReceiptContent("receiptContent", new Tag(Tag.CONTEXT, 0, Module.EXPLICIT_TAGGING));
      components.add(receiptContent);
   }

   // Accessor methods
   // -------------------------------------------------------------------------

   public ObjectIdentifier getIaReceiptMessage() {
      return (ObjectIdentifier) components.get(0);
   }

   public void setIaReceiptMessage(ObjectIdentifier obj) {
      ObjectIdentifier it = getIaReceiptMessage();
      it.value(obj.value());
      components.set(0, it);
   }

   public ReceiptContent getReceiptContent() {
      return (ReceiptContent) components.get(1);
   }

   public void setReceiptContent(ReceiptContent obj) {
      ReceiptContent it = getReceiptContent();
      it.value(obj.value());
      components.set(1, it);
   }

}

// Generated by the cryptix ASN.1 kit on Sun Mar 09 12:59:13 PST 2003
