package com.nightfire.comms.ia3.asn.issue2; // machine generated code. DO NOT EDIT

import cryptix.asn1.lang.*;

public class WithDigest extends Sequence {

   // Constructor(s)
   // -------------------------------------------------------------------------

   /**
    * Constructs a new instance of this type with a blank Name.
    */
   public WithDigest() {
      super("", new Tag(Tag.CONTEXT, 1, true));
   }

   /**
    * Constructs a new instance of this type with a designated Name.
    *
    * @param name the designated Name for this new instance.
    */
   public WithDigest(String name) {
      super(name, new Tag(Tag.CONTEXT, 1, true));
   }

   /**
    * Constructs a new instance of this type with a designated Name and Tag.
    *
    * @param name the designated Name for this new instance.
    * @param tag the designated tag for this new instance.
    */
   public WithDigest(String name, Tag tag) {
      super(name, tag);
   }

   /**
    * Constructs a new instance of this type with a trivial Name and an
    * initial value.
    *
    * @param value the initial value of this instance.
    */
   public WithDigest(Sequence value) {
      this("", value);
   }

   /**
    * Constructs a new instance of this type with a designated Name and an
    * initial value.
    *
    * @param name the designated Name for this new instance.
    * @param value the initial value of this instance.
    */
   public WithDigest(String name, Sequence value) {
      this(name, new Tag(Tag.CONTEXT, 1, true), value);
   }

   /**
    * Constructs a new instance of this type given its Name, Tag and initial
    * value.
    *
    * @param name the designated Name for this new instance.
    * @param tag the specific tag for this instance.
    * @param value the initial value for this instance.
    */
   public WithDigest(String name, Tag tag, Sequence value) {
      super(name, tag, value == null ? null : value.value());
   }

   // Constants and variables
   // -------------------------------------------------------------------------


   // Over-loaded implementation of methods defined in superclass
   // -------------------------------------------------------------------------

   protected void initInternal() {
      super.initInternal();

      IType receiptDigestAlgorithm = new ObjectIdentifier("receiptDigestAlgorithm");
      components.add(receiptDigestAlgorithm);
      IType receiptMessageDigest = new OctetString("receiptMessageDigest");
      components.add(receiptMessageDigest);
   }

   // Accessor methods
   // -------------------------------------------------------------------------

   public ObjectIdentifier getReceiptDigestAlgorithm() {
      return (ObjectIdentifier) components.get(0);
   }

   public void setReceiptDigestAlgorithm(ObjectIdentifier obj) {
      ObjectIdentifier it = getReceiptDigestAlgorithm();
      it.value(obj.value());
      components.set(0, it);
   }

   public OctetString getReceiptMessageDigest() {
      return (OctetString) components.get(1);
   }

   public void setReceiptMessageDigest(OctetString obj) {
      OctetString it = getReceiptMessageDigest();
      it.value(obj.value());
      components.set(1, it);
   }

}

// Generated by the cryptix ASN.1 kit on Sun Mar 09 12:59:13 PST 2003
