PACKAGE = "com.nightfire.framework.state"

PACKAGES = \
	test \

FILES = \
	StateContext.java \
	StateException.java \
	StateRejectedException.java \
	State.java \
	StateMachine.java \
	NoProcessingState.java \
	StateTransitionRuleManager.java \
	StateTransitionRuleManagerBase.java \
	DBStateTransitionRuleManager.java \
	DBStateTransitionRuleManagerFactory.java \
	DBStateMachine.java \

TOP=../../../..

ifndef MAKE_HOME
MAKE_HOME=$(TOP)/makefiles
endif
include $(MAKE_HOME)/package.mk

