PACKAGE = "com.nightfire.spi.common.driver"

FILES = \
	Converter.java \
	MessageProcessorContext.java \
	MessageObject.java \
	MessageProcessor.java \
	MessageProcessorFactory.java \
	MessageProcessorTree.java \
	MessageProcessingDriver.java \
	MessageProcessorBase.java \


PACKAGES = \



TOP=../../../../..

ifndef MAKE_HOME
MAKE_HOME=$(TOP)/makefiles
endif
include $(MAKE_HOME)/package.mk
