PACKAGE = "com.nightfire.spi.neustar_soa.adapter.smartsockets"

FILES = \
	NPACReceiver.java \
	NPACSmartSocketsClient.java \
	Receiver.java \
	SmartSocketsClient.java \
	SmartSocketsReceiver.java \
	SOAClient.java \
	SOAReceiver.java

TOP=../../../../../..

ifndef MAKE_HOME
MAKE_HOME=$(TOP)/makefiles
endif
include $(MAKE_HOME)/package.mk

