PACKAGE = "com.nightfire.servers.CosEvent"

FILES = \
	EventUtils.java \
	Event.java \
	EventStatus.java \
	EventConsumerPolicy.java \
	EventQueue.java \
	OnlyOnceEventConsumerPolicy.java \
	EventConsumerPolicyFactory.java \
	InMemoryEventQueue.java \
	DatabaseEventQueue.java \
	EventQueueFactory.java \
	ProxyPushConsumerImpl.java \
	ProxyPushSupplierImpl.java \
	SupplierAdminImpl.java \
	ConsumerAdminImpl.java \
	EventDeliveryThread.java \
	EventChannelImpl.java \
	AdminChannelImpl.java \
	AdminChannelClient.java \
	EventServer.java \
	ChannelConfigTool.java \

PACKAGES = \
	test \



TOP=../../../..

ifndef MAKE_HOME
MAKE_HOME=$(TOP)/makefiles
endif
include $(MAKE_HOME)/package.mk
