PACKAGE = "com.nightfire.servers.CosEvent.test"

FILES = \
	TestPushConsumer.java              \
	TestPushSupplier.java              \
	SimplePushConsumer.java              \
	SimplePushSupplier.java              \
	EventUnitTest.java              \

    
    
TOP=../../../../..

ifndef MAKE_HOME
MAKE_HOME=$(TOP)/makefiles
endif
include $(MAKE_HOME)/package.mk
