PACKAGE = "com.nightfire.comms.jms"

PACKAGES = \
    handler \

FILES = \
	JMSConsumerHelper.java \
	JMSQueuePollConsumer.java \
    JMSQueueProducer.java \
    JMSQueuePullConsumer.java \
    JMSQueuePushConsumer.java \
    MultiCustomerJMSConsumerServer.java \


TOP=../../../..

ifndef MAKE_HOME
MAKE_HOME=$(TOP)/makefiles
endif
include $(MAKE_HOME)/package.mk