PACKAGE="com.nightfire.manager.common.servicehandler"

TOP=../../../../..

FILES = \
	ManagerServiceHandlerBase.java \
	SaveBundleServiceHandler.java \
	SubmitBundleServiceHandler.java \
	LinkerServiceHandler.java \
	BODetailServiceHandler.java \
	QueryChildrenServiceHandler.java \
	ManagerQueryServiceHandler.java \

ifndef MAKE_HOME
MAKE_HOME=$(TOP)/makefiles
endif

include $(MAKE_HOME)/package.mk
