PACKAGE = "com.nightfire.comms.email"

FILES = \
	SMTPEmailClient.java \
	GetEmailClient.java \
	AsyncEmailServer.java \
	


TOP=../../../..

ifndef MAKE_HOME
MAKE_HOME=$(TOP)/makefiles
endif
include $(MAKE_HOME)/package.mk
