PACKAGE="com.nightfire.spi.neustar_soa.utils"

FILES = \
	RoundRobinAsyncCorbaClient.java \
	RoundRobinCorbaClient.java \
	SOAConstants.java \
	SOAUtility.java \
	TimeZoneUtil.java \
	NancValueMapping.java \
	SOAQueryConstants.java \
	NANCSupportFlag.java \
	NancPropException.java \
	SOAConfiguredSPIDCache.java \
	ConfiguredSOASPIDCacheException.java \
	DynamicComparator.java \
	EndPointSupportFlag.java \

TOP=../../../../..
ifndef MAKE_HOME
MAKE_HOME=$(TOP)/makefiles
endif
include $(MAKE_HOME)/package.mk
