PACKAGE = "com.nightfire.idl"

PACKAGES = \
	RequestHandlerPackage \

IDL = \
	RequestHandler.idl \
	ServerAdmin.idl \

FILES = \
	CorbaServerException.java \
	CorbaServerExceptionHelper.java \
	CorbaServerExceptionHolder.java \
	CorbaServerExceptionType.java \
	CorbaServerExceptionTypeHelper.java \
	CorbaServerExceptionTypeHolder.java \
	InvalidDataException.java \
	InvalidDataExceptionHelper.java \
	InvalidDataExceptionHolder.java \
	InvalidDataExceptionType.java \
	InvalidDataExceptionTypeHelper.java \
	InvalidDataExceptionTypeHolder.java \
	RequestHandler.java \
	RequestHandlerHelper.java \
	RequestHandlerHolder.java \
	RequestHandlerOperations.java \
	RequestHandlerPOA.java \
	RequestHandlerPOATie.java \
	ServerAdmin.java \
	ServerAdminHelper.java \
	ServerAdminHolder.java \
	ServerAdminOperations.java \
	_RequestHandlerStub.java \
	_ServerAdminStub.java \

TOP=../../..
ifndef MAKE_HOME
MAKE_HOME=$(TOP)/makefiles
endif
include $(MAKE_HOME)/package.mk

